**Section 4: Large Language Models (LLMs) and retrieval-based AI**

**1- Data preprocessing & retrieval setup**

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

# creating a new dataset for the LLM section
amazon_llm = pd.read_csv("amazon_reviews.csv")

In [ ]:
## head dataset
amazon_llm.head()

,marketplace,customer_id,review_id,product_id,product_parent,product_title,product_category,star_rating,helpful_votes,total_votes,vine,verified_purchase,review_headline,review_body,review_date
0,US,32158956,R1KKOXHNI8MSXU,B01KL6O72Y,24485154,Easy Tool Stainless Steel Fruit Pineapple Core...,Apparel,4,0,0,N,Y,★ THESE REALLY DO WORK GREAT WITH SOME TWEAKING ★,"These Really Do Work Great, But You Do Need To...",14-01-2013
1,US,2714559,R26SP2OPDK4HT7,B01ID3ZS5W,363128556,V28 Women Cowl Neck Knit Stretchable Elasticit...,Apparel,5,1,2,N,Y,Favorite for winter. Very warm!,I love this dress. Absolute favorite for winte...,04-03-2014
2,US,12608825,RWQEDYAX373I1,B01I497BGY,811958549,James Fiallo Men's 12-Pairs Low Cut Athletic S...,Apparel,5,0,0,N,Y,Great Socks for the money.,"Nice socks, great colors, just enough support ...",12-07-2015
3,US,25482800,R231YI7R4GPF6J,B01HDXFZK6,692205728,Belfry Gangster 100% Wool Stain-Resistant Crus...,Apparel,5,0,0,N,Y,Slick hat!,"I bought this for my husband and WOW, this is ...",03-06-2015
4,US,9310286,R3KO3W45DD0L1K,B01G6MBEBY,431150422,JAEDEN Women's Beaded Spaghetti Straps Sexy Lo...,Apparel,5,0,0,N,Y,I would do it again!,Perfect dress and the customer service was awe...,12-06-2015

In [3]:
## pre processing needed it for LLMs
# check missing values
amazon_llm.isnull().sum()

marketplace           0
customer_id           0
review_id             0
product_id            0
product_parent        0
product_title         0
product_category      1
star_rating           1
helpful_votes         1
total_votes           1
vine                  1
verified_purchase     1
review_headline       1
review_body          73
review_date          10
dtype: int64

In [4]:
# Remove duplicate reviews
amazon_llm = amazon_llm.drop_duplicates(subset=['review_body'])

In [5]:

# Remove rows with missing product titles or reviews
amazon_llm = amazon_llm.dropna(
    subset=[
        "product_title",
        "review_body"
    ]
)

In [6]:
# Reset index
amazon_llm.reset_index(drop=True, inplace=True)

In [7]:
# Implement fuzzy matching for retrieving relevant product details
!pip install rapidfuzz
from rapidfuzz import process
## displaying some products tittle
amazon_llm["product_title"].head()

Collecting rapidfuzz
  Downloading rapidfuzz-3.14.5-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (12 kB)
Downloading rapidfuzz-3.14.5-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (3.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 41.1 MB/s eta 0:00:00
Installing collected packages: rapidfuzz
Successfully installed rapidfuzz-3.14.5

0    Easy Tool Stainless Steel Fruit Pineapple Core...
1    V28 Women Cowl Neck Knit Stretchable Elasticit...
2    James Fiallo Men's 12-Pairs Low Cut Athletic S...
3    Belfry Gangster 100% Wool Stain-Resistant Crus...
4    JAEDEN Women's Beaded Spaghetti Straps Sexy Lo...
Name: product_title, dtype: object

In [8]:
## Creating a list  of product Titles
product_titles = amazon_llm["product_title"].dropna().unique().tolist()
### SAVING THE LIST OF PRODUCTS TO REUSE IT LATER

In [9]:
## Performing Fuzzy Machine
# User input
search_query = "wireles mouse"

# Find the closest match
match = process.extractOne(
    search_query,
    product_titles
)

print(match)

('Marvel Silver Surfer mouse pad', 85.5, 26147)

In [10]:
## Retriving the products Details
best_match = match[0]
product_details = amazon_llm[
    amazon_llm["product_title"] == best_match
]

product_details.head()

,marketplace,customer_id,review_id,product_id,product_parent,product_title,product_category,star_rating,helpful_votes,total_votes,vine,verified_purchase,review_headline,review_body,review_date
60345,US,39130847,R3DKMCJ6NKBXTW,B00WY3IAC6,263234733,Marvel Silver Surfer mouse pad,Apparel,1.0,0.0,0.0,N,N,Stand up,What do you get when you cross a non comic boo...,20-07-2015

In [11]:
# Use vector databases (FAISS, Pinecone) to manage product embeddings
# Install required libraries
!pip install faiss-cpu sentence-transformers
import faiss
import numpy as np
from sentence_transformers import SentenceTransformer

Collecting faiss-cpu
  Downloading faiss_cpu-1.14.3-cp310-abi3-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (7.8 kB)
Requirement already satisfied: sentence-transformers in /usr/local/lib/python3.12/dist-packages (5.6.0)
Requirement already satisfied: numpy>=1.25 in /usr/local/lib/python3.12/dist-packages (from faiss-cpu) (2.0.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from faiss-cpu) (26.2)
Requirement already satisfied: transformers<6.0.0,>=4.41.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (5.13.1)
Requirement already satisfied: huggingface-hub>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.23.0)
Requirement already satisfied: torch>=1.11.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (2.11.0+cpu)
Requirement already satisfied: scikit-learn>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.6.1)
Requirement already satisfied: scipy>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (1.16.3)
Requirement already satisfied: typing_extensions>=4.5.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.16.0)
Requirement already satisfied: tqdm>=4.0.0 in /usr/local/lib/python3.12/dist-packages (from sentence-transformers) (4.67.3)
Requirement already satisfied: click<9.0.0,>=8.4.2 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (8.4.2)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (3.29.7)
Requirement already satisfied: fsspec>=2023.5.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (2025.3.0)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (1.5.1)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (0.28.1)
Requirement already satisfied: pyyaml>=5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub>=0.23.0->sentence-transformers) (6.0.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.0->sentence-transformers) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn>=0.22.0->sentence-transformers) (3.6.0)
Requirement already satisfied: setuptools<82 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (75.2.0)
Requirement already satisfied: sympy>=1.13.3 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (1.14.0)
Requirement already satisfied: networkx>=2.5.1 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.6.1)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from torch>=1.11.0->sentence-transformers) (3.1.6)
Requirement already satisfied: regex>=2025.10.22 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (2025.11.3)
Requirement already satisfied: tokenizers<=0.23.0,>=0.22.0 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.22.2)
Requirement already satisfied: typer in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.26.8)
Requirement already satisfied: safetensors>=0.8.0 in /usr/local/lib/python3.12/dist-packages (from transformers<6.0.0,>=4.41.0->sentence-transformers) (0.8.0)
Requirement already satisfied: anyio in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (4.14.2)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (2026.6.17)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (1.0.9)
Requirement already satisfied: idna in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (3.18)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->huggingface-hub>=0.23.0->sentence-transformers) (0.16.0)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from sympy>=1.13.3->torch>=1.11.0->sentence-transformers) (1.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->torch>=1.11.0->sentence-transformers) (3.0.3)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.12/dist-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (13.9.4)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (0.0.4)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer->transformers<6.0.0,>=4.41.0->sentence-transformers) (0.1.2)
Downloading faiss_cpu-1.14.3-cp310-abi3-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (18.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.5/18.5 MB 63.1 MB/s eta 0:00:00
Installing collected packages: faiss-cpu
Successfully installed faiss-cpu-1.14.3

In [ ]:
# Load a pretrained sentence embedding model
embedding_model = SentenceTransformer('all-MiniLM-L6-v2')

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [ ]:
# Generate embeddings from product titles
product_embeddings = embedding_model.encode(
    amazon_llm["product_title"].tolist(),
    convert_to_numpy=True
)

In [ ]:
# Create a FAISS index
dimension = product_embeddings.shape[1]

index = faiss.IndexFlatL2(dimension)

index.add(product_embeddings)

print("Number of indexed products:", index.ntotal)

Number of indexed products: 32479

In [ ]:
# Example search query
query = "wireless bluetooth headphones"

# Convert the query into an embedding
query_embedding = embedding_model.encode(
    [query],
    convert_to_numpy=True
)

# Retrieve the 5 most similar products
distances, indices = index.search(
    query_embedding,
    k=5
)

# Display results
amazon_llm.iloc[indices[0]][["product_title"]]

                                           product_title
1342   Beats Solo HD On-Ear Headphone (Certified Refu...
13452  Royce Universal Bluetooth-Based Tracking Devic...
13453  Royce Universal Bluetooth-Based Tracking Devic...
2402   Dealkoo Selfie Monopod Shooter with Built-In B...
27865                       Mens Blue Contrast Tracksuit

**2- Prompt engineering for LLM optimization**

In [ ]:
# Design structured prompts to generate high-quality product descriptions

# Example product information
product_title = "Wireless Bluetooth Headphones"

review = """
Customers appreciate the excellent sound quality,
comfortable fit, long battery life, and reliable Bluetooth connectivity.
"""

# Structured Prompt
prompt = f"""
You are an AI assistant specializing in e-commerce.

Using the information below, write a professional product description.

Product Title:
{product_title}

Customer Review:
{review}

Requirements:
- Write 3–5 sentences.
- Highlight the key product features.
- Use a professional and engaging tone.
- Do not copy the review verbatim.
- Focus on customer benefits.

Product Description:
"""

print(prompt)

You are an AI assistant specializing in e-commerce.

Using the information below, write a professional product description.

Product Title:
Wireless Bluetooth Headphones

Customer Review:

Customers appreciate the excellent sound quality,
comfortable fit, long battery life, and reliable Bluetooth connectivity.


Requirements:
- Write 3–5 sentences.
- Highlight the key product features.
- Use a professional and engaging tone.
- Do not copy the review verbatim.
- Focus on customer benefits.

Product Description:

**Observation:**

Providing structured instructions helps the LLM generate more consistent, informative, and engaging product descriptions while reducing irrelevant or repetitive responses.

Business Insight

Well-designed prompts improve the quality of AI-generated product descriptions, helping e-commerce businesses create compelling product listings more efficiently. This can enhance customer engagement, improve search visibility, and reduce the time required for manual content creation.

In [ ]:
## Apply temperature and top-k sampling to enhance response diversity
from transformers import pipeline
# load a text generation model
generator = pipeline(
    task="text-generation",
    model="gpt2"
)
# Prompt
prompt = """
You are an AI assistant specializing in e-commerce product descriptions.

Using the product information below, generate a clear, engaging, and professional product description.

Product Title:
Wireless Bluetooth Headphones

Customer Review:
Customers appreciate the excellent sound quality, comfortable fit, long battery life, and reliable Bluetooth connectivity.

Requirements:
- Write 3–5 sentences.
- Highlight the key product features.
- Use a professional and persuasive tone.
- Focus on customer benefits rather than technical specifications.
- Do not copy the customer review verbatim.

Product Description:
"""
## generate text
response = generator(
    prompt,
    max_length=200,
    do_sample=True,
    temperature=0.7,
    top_k=50
)

# Display the generated text
print(response[0]["generated_text"])

config.json:   0%|          | 0.00/665 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/548M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/124 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/26.0 [00:00<?, ?B/s]

vocab.json:   0%|          | 0.00/1.04M [00:00<?, ?B/s]

merges.txt:   0%|          | 0.00/456k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/1.36M [00:00<?, ?B/s]

[transformers] Passing `generation_config` together with generation-related arguments=({'temperature', 'do_sample', 'top_k', 'max_length'}) is deprecated and will be removed in future versions. Please pass either a `generation_config` object OR all generation parameters explicitly, but not both.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Both `max_new_tokens` (=256) and `max_length`(=200) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Ignoring clean_up_tokenization_spaces=True for BPE tokenizer GPT2Tokenizer. The clean_up_tokenization post-processing step is designed for WordPiece tokenizers and is destructive for BPE (it strips spaces before punctuation). Set clean_up_tokenization_spaces=False to suppress this warning, or set clean_up_tokenization_spaces_for_bpe_even_though_it_will_corrupt_output=True to force cleanup anyway.

You are an AI assistant specializing in e-commerce product descriptions.

Using the product information below, generate a clear, engaging, and professional product description.

Product Title:
Wireless Bluetooth Headphones

Customer Review:
Customers appreciate the excellent sound quality, comfortable fit, long battery life, and reliable Bluetooth connectivity.

Requirements:
- Write 3–5 sentences.
- Highlight the key product features.
- Use a professional and persuasive tone.
- Focus on customer benefits rather than technical specifications.
- Do not copy the customer review verbatim.

Product Description:

Wireless Bluetooth Headphones

Product Description:

Wireless Bluetooth Headphones is a wireless wireless Bluetooth Headphone that is capable of receiving, sending, and receiving data from the Bluetooth Smart-5 and its connected devices. The Bluetooth Headphone can also receive data from the Bluetooth Smart-5, and can be used for the following:

- Voice Dialing and Bluetooth Calling

- Bluetooth Calling

- Phone Calling

- Phone Calling

- Bluetooth Calling

- Texting

- Texting

- SMS

- Bluetooth Calling

- Texting

- Bluetooth Calling

- Texting

- Phone Calling

- Texting

- Texting

- Phone Calling

- Texting

- SMS

- Bluetooth Calling

- Texting

- Texting

- SMS

- Bluetooth Calling

- Texting

- Texting

- Texting

- SMS

- Bluetooth Calling

- Texting

- Texting

- Texting

- SMS

- Bluetooth Calling

- Texting

- Texting

- Texting

- SMS

-

**3- Retrieval-Augmented Generation (RAG) implementation:**

In [ ]:
## Integrate retrieval-based search with LLM-generated content

# User search query
query = "Wireless Bluetooth Headphones"

# Convert query into an embedding
query_embedding = embedding_model.encode(
    [query],
    convert_to_numpy=True
)

# Retrieve the most similar product
distances, indices = index.search(
    query_embedding,
    k=1
)

# Retrieve product information
retrieved_product = amazon_llm.iloc[indices[0][0]]

print("Retrieved Product:")
print(retrieved_product["product_title"])

Retrieved Product:
Beats Solo HD On-Ear Headphone (Certified Refurbished)

In [ ]:
## creating the prompt
prompt = f"""
You are an AI assistant specializing in e-commerce.

Generate a professional product description using the retrieved product information.

Product Title:
{retrieved_product["product_title"]}

Customer Review:
{retrieved_product["review_body"]}

Requirements:
- Write 3–5 sentences.
- Highlight key product features.
- Use a professional tone.
- Do not copy the review exactly.

Product Description:
"""

print(prompt)

## generating response
response = generator(

    prompt,

    max_new_tokens=100,

    temperature=0.7,

    top_k=50,

    do_sample=True

)

print(response[0]["generated_text"])

[transformers] Passing `generation_config` together with generation-related arguments=({'max_new_tokens', 'temperature', 'do_sample', 'top_k'}) is deprecated and will be removed in future versions. Please pass either a `generation_config` object OR all generation parameters explicitly, but not both.
[transformers] Setting `pad_token_id` to `eos_token_id`:50256 for open-end generation.
[transformers] Both `max_new_tokens` (=100) and `max_length`(=50) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

You are an AI assistant specializing in e-commerce.

Generate a professional product description using the retrieved product information.

Product Title:
Beats Solo HD On-Ear Headphone (Certified Refurbished)

Customer Review:
Does it come with the pouch ?

Requirements:
- Write 3–5 sentences.
- Highlight key product features.
- Use a professional tone.
- Do not copy the review exactly.

Product Description:


You are an AI assistant specializing in e-commerce.

Generate a professional product description using the retrieved product information.

Product Title:
Beats Solo HD On-Ear Headphone (Certified Refurbished)

Customer Review:
Does it come with the pouch ?

Requirements:
- Write 3–5 sentences.
- Highlight key product features.
- Use a professional tone.
- Do not copy the review exactly.

Product Description:

Beats Solo HD On-Ear Headphone (Certified Refurbished)

Product name:

Beats Solo HD On-Ear Headphone (Certified Refurbished)

Product size:

Size of the headphones.

Material:

- 1/2″ x 1″

- 1/2″ x 1″

- 1/2″ x 1″

- 1/2″ x 1″

- 1

In [ ]:
## Use LangChain or similar frameworks for RAG workflows
# Install LangChain
!pip install langchain langchain-community
from langchain_core.prompts import PromptTemplate

Requirement already satisfied: langchain in /usr/local/lib/python3.12/dist-packages (1.3.11)
Requirement already satisfied: langchain-community in /usr/local/lib/python3.12/dist-packages (0.4.2)
Requirement already satisfied: langchain-core<2.0.0,>=1.4.7 in /usr/local/lib/python3.12/dist-packages (from langchain) (1.4.8)
Requirement already satisfied: langgraph<1.3.0,>=1.2.5 in /usr/local/lib/python3.12/dist-packages (from langchain) (1.2.6)
Requirement already satisfied: pydantic<3.0.0,>=2.7.4 in /usr/local/lib/python3.12/dist-packages (from langchain) (2.13.4)
Requirement already satisfied: aiohttp<4.0.0,>=3.8.3 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (3.14.1)
Requirement already satisfied: httpx-sse<1.0.0,>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (0.4.3)
Requirement already satisfied: langchain-classic<2.0.0,>=1.0.7 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (1.0.8)
Requirement already satisfied: langsmith<1.0.0,>=0.1.125 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (0.9.1)
Requirement already satisfied: numpy>=1.26.2 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (2.0.2)
Requirement already satisfied: pydantic-settings<3.0.0,>=2.10.1 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (2.14.2)
Requirement already satisfied: pyyaml<7.0.0,>=5.3.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (6.0.3)
Requirement already satisfied: requests<3.0.0,>=2.32.5 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (2.34.2)
Requirement already satisfied: sqlalchemy<3.0.0,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (2.0.51)
Requirement already satisfied: tenacity!=8.4.0,<10.0.0,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from langchain-community) (9.1.4)
Requirement already satisfied: aiohappyeyeballs>=2.5.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (2.6.2)
Requirement already satisfied: aiosignal>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.4.0)
Requirement already satisfied: attrs>=17.3.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (26.1.0)
Requirement already satisfied: frozenlist>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.8.0)
Requirement already satisfied: multidict<7.0,>=4.5 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (6.7.1)
Requirement already satisfied: propcache>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (0.5.2)
Requirement already satisfied: typing_extensions>=4.4 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (4.15.0)
Requirement already satisfied: yarl<2.0,>=1.17.0 in /usr/local/lib/python3.12/dist-packages (from aiohttp<4.0.0,>=3.8.3->langchain-community) (1.24.2)
Requirement already satisfied: langchain-text-splitters<2.0.0,>=1.1.2 in /usr/local/lib/python3.12/dist-packages (from langchain-classic<2.0.0,>=1.0.7->langchain-community) (1.1.2)
Requirement already satisfied: jsonpatch<2.0.0,>=1.33.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.4.7->langchain) (1.33)
Requirement already satisfied: langchain-protocol>=0.0.17 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.4.7->langchain) (0.0.18)
Requirement already satisfied: packaging>=23.2.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.4.7->langchain) (26.2)
Requirement already satisfied: uuid-utils<1.0,>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from langchain-core<2.0.0,>=1.4.7->langchain) (0.16.2)
Requirement already satisfied: langgraph-checkpoint<5.0.0,>=4.1.0 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.3.0,>=1.2.5->langchain) (4.1.1)
Requirement already satisfied: langgraph-prebuilt<1.2.0,>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.3.0,>=1.2.5->langchain) (1.1.0)
Requirement already satisfied: langgraph-sdk<0.5.0,>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.3.0,>=1.2.5->langchain) (0.4.2)
Requirement already satisfied: xxhash>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from langgraph<1.3.0,>=1.2.5->langchain) (3.7.1)
Requirement already satisfied: anyio>=3.5.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (4.14.0)
Requirement already satisfied: distro>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (1.9.0)
Requirement already satisfied: httpx<1,>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (0.28.1)
Requirement already satisfied: orjson>=3.9.14 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (3.11.9)
Requirement already satisfied: requests-toolbelt>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (1.0.0)
Requirement already satisfied: sniffio>=1.1 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (1.3.1)
Requirement already satisfied: websockets>=15.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (15.0.1)
Requirement already satisfied: zstandard>=0.23.0 in /usr/local/lib/python3.12/dist-packages (from langsmith<1.0.0,>=0.1.125->langchain-community) (0.25.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (2.46.4)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3.0.0,>=2.7.4->langchain) (0.4.2)
Requirement already satisfied: python-dotenv>=0.21.0 in /usr/local/lib/python3.12/dist-packages (from pydantic-settings<3.0.0,>=2.10.1->langchain-community) (1.2.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.5->langchain-community) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.5->langchain-community) (3.18)
Requirement already satisfied: urllib3<3,>=1.26 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.5->langchain-community) (2.5.0)
Requirement already satisfied: certifi>=2023.5.7 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.32.5->langchain-community) (2026.6.17)
Requirement already satisfied: greenlet>=1 in /usr/local/lib/python3.12/dist-packages (from sqlalchemy<3.0.0,>=1.4.0->langchain-community) (3.5.2)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain-community) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1,>=0.23.0->langsmith<1.0.0,>=0.1.125->langchain-community) (0.16.0)
Requirement already satisfied: jsonpointer>=1.9 in /usr/local/lib/python3.12/dist-packages (from jsonpatch<2.0.0,>=1.33.0->langchain-core<2.0.0,>=1.4.7->langchain) (3.1.1)
Requirement already satisfied: ormsgpack>=1.12.0 in /usr/local/lib/python3.12/dist-packages (from langgraph-checkpoint<5.0.0,>=4.1.0->langgraph<1.3.0,>=1.2.5->langchain) (1.12.2)

In [ ]:
# Create a reusable prompt template

template = """
You are an AI assistant specializing in e-commerce.

Using the retrieved product information below, generate a professional product description.

Product Title:
{product_title}

Customer Review:
{review_body}

Requirements:
- Write 3–5 sentences.
- Highlight key product features.
- Use a professional tone.
- Focus on customer benefits.
- Do not copy the review exactly.

Product Description:
"""

prompt = PromptTemplate(
    input_variables=["product_title", "review_body"],
    template=template
)

In [ ]:
# using FAISS
#  User query
query = "Wireless Bluetooth Headphones"

# Convert query into an embedding
query_embedding = embedding_model.encode(
    [query],
    convert_to_numpy=True
)

# Search the FAISS index
distances, indices = index.search(
    query_embedding,
    k=1
)

# Retrieve product information
retrieved_product = amazon_llm.iloc[indices[0][0]]

print(retrieved_product["product_title"])

Beats Solo HD On-Ear Headphone (Certified Refurbished)

In [ ]:
## FORMATING the prompt with LangChain

formatted_prompt = prompt.format(

    product_title=retrieved_product["product_title"],

    review_body=retrieved_product["review_body"]

)

print(formatted_prompt)

You are an AI assistant specializing in e-commerce.

Using the retrieved product information below, generate a professional product description.

Product Title:
Beats Solo HD On-Ear Headphone (Certified Refurbished)

Customer Review:
Does it come with the pouch ?

Requirements:
- Write 3–5 sentences.
- Highlight key product features.
- Use a professional tone.
- Focus on customer benefits.
- Do not copy the review exactly.

Product Description:

**Observation:**

Business Insight

LangChain improves Retrieval-Augmented Generation workflows by efficiently combining retrieved product information with structured prompts. This enables businesses to build scalable AI applications that generate accurate, context-aware product descriptions and enhance customer search experiences.

In [ ]:
# Fine-tune retrieval systems to improve result relevance



query = "Wireless Bluetooth Headphones"

query_embedding = embedding_model.encode(
    [query],
    convert_to_numpy=True
)

distances, indices = index.search(

    query_embedding,

    k=5 ## this K CHANGED INSTEAD OF 1 SO I CAN RETRIVE MORE

)

In [ ]:
## Displaying the results

retrieved_products = amazon_llm.iloc[
    indices[0]
]

retrieved_products[
    [
        "product_title",
        "star_rating"
    ]
]

                                           product_title  star_rating
1342   Beats Solo HD On-Ear Headphone (Certified Refu...          5.0
13452  Royce Universal Bluetooth-Based Tracking Devic...          5.0
13453  Royce Universal Bluetooth-Based Tracking Devic...          5.0
2402   Dealkoo Selfie Monopod Shooter with Built-In B...          5.0
27865                       Mens Blue Contrast Tracksuit          4.0

In [ ]:
## selecting the best  products
best_product = retrieved_products.sort_values(

    by="star_rating",

    ascending=False

).iloc[0]

print(best_product["product_title"])

Beats Solo HD On-Ear Headphone (Certified Refurbished)

In [ ]:
## using the best product
formatted_prompt = prompt.format(

    product_title=best_product["product_title"],

    review_body=best_product["review_body"]

)

print(formatted_prompt)

You are an AI assistant specializing in e-commerce.

Using the retrieved product information below, generate a professional product description.

Product Title:
Beats Solo HD On-Ear Headphone (Certified Refurbished)

Customer Review:
Does it come with the pouch ?

Requirements:
- Write 3–5 sentences.
- Highlight key product features.
- Use a professional tone.
- Focus on customer benefits.
- Do not copy the review exactly.

Product Description:

**Observation**

improves customer search experiences, and supports more effective product recommendation systems in e-commerce.

**4- LLM fine-tuning & model selection**

In [12]:

# Create Sample Dataset for Model Development


amazon_sample = (
    amazon_llm
    .sample(n=5000, random_state=42)
    .reset_index(drop=True)
)

print("Original Shape:", amazon_llm.shape)
print("Sample Shape:", amazon_sample.shape)

amazon_sample.head()

Original Shape: (102321, 15)
Sample Shape: (5000, 15)

,marketplace,customer_id,review_id,product_id,product_parent,product_title,product_category,star_rating,helpful_votes,total_votes,vine,verified_purchase,review_headline,review_body,review_date
0,US,21223367,RLVM2W29IKACG,B00ZW4BZBC,791152338,Expression Tees This Is My Fight Song Womens T...,Apparel,1.0,0.0,6.0,N,Y,One Star,Want to send it back but don't know how.,17-08-2015
1,US,544877,R10H7PIV7NPZ3W,B00XU3UVBM,900611195,MR. R Men's Summer Linen Slim Fit Solid Flat F...,Apparel,5.0,0.0,0.0,N,Y,I like it,I like it. will buy other color,02-06-2015
2,US,11715044,R1ALQE4SHBNB75,B00WFUGU7U,12847179,21secret Summer Elegant Batwing Bohemian Casua...,Apparel,4.0,0.0,0.0,N,Y,Four Stars,"Nice fabric. Comfortable and diverse, you can ...",02-08-2015
3,US,3103934,RYPMXU4BA75KN,B00VWICSSG,35957486,Free2mys Summer 2015 Printing Women Sleeveless...,Apparel,2.0,0.0,0.0,N,Y,Not sure if I order the wrong size or a ...,Not sure if I order the wrong size or a mistak...,19-08-2015
4,US,3981025,R3VO53QV6AK36G,B00WDUP62C,852005194,HOLRAN The Future Diary Gasai Yuno set 2nd Cos...,Apparel,4.0,0.0,0.0,N,Y,Order 2 sizes up!!,"Pros: Came 3 weeks early, decent price, qualit...",12-05-2015

In [ ]:
#Fine-tune open-source LLMs (e.g., Mistral, LLaMA, Falcon) on product data

# Note:
# A full fine-tuning process for large language models such as Mistral,
# LLaMA, or Falcon requires significant computational resources (high-memory GPUs)
# and extended training time. Therefore, this project demonstrates the
# fine-tuning workflow by preparing the training dataset and selecting
# a pretrained model rather than executing the complete fine-tuning process.

In [13]:

# Fine-Tune Open-Source LLMs (Workflow Demonstration)


# Example model
model_name = "mistralai/Mistral-7B-Instruct-v0.2"

print("Selected Model:", model_name)

# Example training dataset
training_data = amazon_sample[
    [
        "product_title",
        "review_body"
    ]
]

print(training_data.head())

Selected Model: mistralai/Mistral-7B-Instruct-v0.2
                                       product_title  \
0  Expression Tees This Is My Fight Song Womens T...
1  MR. R Men's Summer Linen Slim Fit Solid Flat F...
2  21secret Summer Elegant Batwing Bohemian Casua...
3  Free2mys Summer 2015 Printing Women Sleeveless...
4  HOLRAN The Future Diary Gasai Yuno set 2nd Cos...

                                         review_body
0           Want to send it back but don't know how.
1                    I like it. will buy other color
2  Nice fabric. Comfortable and diverse, you can ...
3  Not sure if I order the wrong size or a mistak...
4  Pros: Came 3 weeks early, decent price, qualit...

In [14]:
# pre training the data
training_data["instruction"] = (
    "Generate a professional product description."
)

training_data["input"] = training_data["product_title"]

training_data["output"] = training_data["review_body"]

training_data.head()

/tmp/ipykernel_877/3280633885.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  training_data["instruction"] = (
/tmp/ipykernel_877/3280633885.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  training_data["input"] = training_data["product_title"]
/tmp/ipykernel_877/3280633885.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  training_data["output"] = training_data["review_body"]

,product_title,review_body,instruction,input,output
0,Expression Tees This Is My Fight Song Womens T...,Want to send it back but don't know how.,Generate a professional product description.,Expression Tees This Is My Fight Song Womens T...,Want to send it back but don't know how.
1,MR. R Men's Summer Linen Slim Fit Solid Flat F...,I like it. will buy other color,Generate a professional product description.,MR. R Men's Summer Linen Slim Fit Solid Flat F...,I like it. will buy other color
2,21secret Summer Elegant Batwing Bohemian Casua...,"Nice fabric. Comfortable and diverse, you can ...",Generate a professional product description.,21secret Summer Elegant Batwing Bohemian Casua...,"Nice fabric. Comfortable and diverse, you can ..."
3,Free2mys Summer 2015 Printing Women Sleeveless...,Not sure if I order the wrong size or a mistak...,Generate a professional product description.,Free2mys Summer 2015 Printing Women Sleeveless...,Not sure if I order the wrong size or a mistak...
4,HOLRAN The Future Diary Gasai Yuno set 2nd Cos...,"Pros: Came 3 weeks early, decent price, qualit...",Generate a professional product description.,HOLRAN The Future Diary Gasai Yuno set 2nd Cos...,"Pros: Came 3 weeks early, decent price, qualit..."

In [ ]:
## Adapt LLMs for e-commerce applications using transfer learning

In [15]:
## adapting
# Example pretrained model
pretrained_model = "mistralai/Mistral-7B-Instruct-v0.2"

print("Pretrained Model:", pretrained_model)

# Prepare product information for adaptation
ecommerce_data = amazon_sample[
    [
        "product_title",
        "review_body"
    ]
].copy()

# Example instruction for transfer learning
ecommerce_data["instruction"] = (
    "Generate a professional product description for an e-commerce website."
)

ecommerce_data.head()

Pretrained Model: mistralai/Mistral-7B-Instruct-v0.2

,product_title,review_body,instruction
0,Expression Tees This Is My Fight Song Womens T...,Want to send it back but don't know how.,Generate a professional product description fo...
1,MR. R Men's Summer Linen Slim Fit Solid Flat F...,I like it. will buy other color,Generate a professional product description fo...
2,21secret Summer Elegant Batwing Bohemian Casua...,"Nice fabric. Comfortable and diverse, you can ...",Generate a professional product description fo...
3,Free2mys Summer 2015 Printing Women Sleeveless...,Not sure if I order the wrong size or a mistak...,Generate a professional product description fo...
4,HOLRAN The Future Diary Gasai Yuno set 2nd Cos...,"Pros: Came 3 weeks early, decent price, qualit...",Generate a professional product description fo...

**Side Note:**

This section demonstrates how a pretrained LLM can be adapted for
e-commerce applications using transfer learning. Executing a full
transfer learning process requires high-performance GPUs and extended
training time, which are beyond the scope of this capstone project.

In [ ]:
# Note:
# This section demonstrates how a pretrained LLM can be adapted for
# e-commerce applications using transfer learning. Executing a full
# transfer learning process requires high-performance GPUs and extended
# training time, which are beyond the scope of this capstone project.

Compare performance across models like GPT-4, LLaMA-2, etc

In [17]:

# Compare Performance Across Popular Open-Source LLMs


import pandas as pd

comparison = pd.DataFrame({

    "Model":[
        "GPT-4",
        "LLaMA-2",
        "Mistral 7B",
        "Falcon 7B"
    ],

    "Type":[
        "Closed-source",
        "Open-source",
        "Open-source",
        "Open-source"
    ],

    "Strength":[
        "High reasoning and text generation",
        "Strong conversational abilities",
        "Fast inference and efficient performance",
        "Large-scale text generation"
    ],

    "Typical Use":[
        "Chatbots, content generation",
        "Research, assistants",
        "RAG applications, summarization",
        "Question answering, text generation"
    ]

})

comparison

,Model,Type,Strength,Typical Use
0,GPT-4,Closed-source,High reasoning and text generation,"Chatbots, content generation"
1,LLaMA-2,Open-source,Strong conversational abilities,"Research, assistants"
2,Mistral 7B,Open-source,Fast inference and efficient performance,"RAG applications, summarization"
3,Falcon 7B,Open-source,Large-scale text generation,"Question answering, text generation"

**Side Note:***
GPT-4 generally provides the strongest reasoning and language generation capabilities but is proprietary. Open-source models such as LLaMA-2, Mistral, and Falcon offer greater flexibility for customization and deployment, making them suitable for domain-specific applications like e-commerce.

**5- Application development & deployment**

In [ ]:
# Build a simple web interface for user interaction
!pip install gradio
import gradio as gr

Requirement already satisfied: gradio in /usr/local/lib/python3.12/dist-packages (6.19.0)
Requirement already satisfied: anyio<5.0,>=3.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (4.14.0)
Requirement already satisfied: brotli>=1.1.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (1.2.0)
Requirement already satisfied: fastapi<1.0,>=0.115.2 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.138.0)
Requirement already satisfied: gradio-client==2.5.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (2.5.0)
Requirement already satisfied: groovy~=0.1 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.1.2)
Requirement already satisfied: hf-gradio<1.0,>=0.4.1 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.4.1)
Requirement already satisfied: httpx<1.0,>=0.24.1 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.28.1)
Requirement already satisfied: huggingface-hub<2.0,>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (1.20.1)
Requirement already satisfied: jinja2<4.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (3.1.6)
Requirement already satisfied: markupsafe<4.0,>=2.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (3.0.3)
Requirement already satisfied: numpy<3.0,>=1.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (2.0.2)
Requirement already satisfied: orjson~=3.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (3.11.9)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from gradio) (26.2)
Requirement already satisfied: pandas<4.0,>=1.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (2.2.2)
Requirement already satisfied: pillow<13.0,>=8.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (11.3.0)
Requirement already satisfied: pydantic<=3.0,>=2.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (2.13.4)
Requirement already satisfied: pydub<1.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.25.1)
Requirement already satisfied: python-multipart<1.0,>=0.0.18 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.0.32)
Requirement already satisfied: pytz>=2017.2 in /usr/local/lib/python3.12/dist-packages (from gradio) (2025.2)
Requirement already satisfied: pyyaml<7.0,>=5.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (6.0.3)
Requirement already satisfied: safehttpx<0.2.0,>=0.1.7 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.1.7)
Requirement already satisfied: semantic-version~=2.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (2.10.0)
Requirement already satisfied: starlette<2.0,>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from gradio) (1.3.1)
Requirement already satisfied: tomlkit<0.15.0,>=0.12.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.14.0)
Requirement already satisfied: typer<1.0,>=0.12 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.25.1)
Requirement already satisfied: typing-extensions~=4.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (4.15.0)
Requirement already satisfied: uvicorn>=0.14.0 in /usr/local/lib/python3.12/dist-packages (from gradio) (0.49.0)
Requirement already satisfied: fsspec in /usr/local/lib/python3.12/dist-packages (from gradio-client==2.5.0->gradio) (2025.3.0)
Requirement already satisfied: idna>=2.8 in /usr/local/lib/python3.12/dist-packages (from anyio<5.0,>=3.0->gradio) (3.18)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from fastapi<1.0,>=0.115.2->gradio) (0.4.2)
Requirement already satisfied: annotated-doc>=0.0.2 in /usr/local/lib/python3.12/dist-packages (from fastapi<1.0,>=0.115.2->gradio) (0.0.4)
Requirement already satisfied: certifi in /usr/local/lib/python3.12/dist-packages (from httpx<1.0,>=0.24.1->gradio) (2026.6.17)
Requirement already satisfied: httpcore==1.* in /usr/local/lib/python3.12/dist-packages (from httpx<1.0,>=0.24.1->gradio) (1.0.9)
Requirement already satisfied: h11>=0.16 in /usr/local/lib/python3.12/dist-packages (from httpcore==1.*->httpx<1.0,>=0.24.1->gradio) (0.16.0)
Requirement already satisfied: click>=8.4.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.2.0->gradio) (8.4.2)
Requirement already satisfied: filelock>=3.10.0 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.2.0->gradio) (3.29.4)
Requirement already satisfied: hf-xet<2.0.0,>=1.5.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.2.0->gradio) (1.5.1)
Requirement already satisfied: tqdm>=4.42.1 in /usr/local/lib/python3.12/dist-packages (from huggingface-hub<2.0,>=1.2.0->gradio) (4.67.3)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=1.0->gradio) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<4.0,>=1.0->gradio) (2026.2)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<=3.0,>=2.0->gradio) (0.7.0)
Requirement already satisfied: pydantic-core==2.46.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<=3.0,>=2.0->gradio) (2.46.4)
Requirement already satisfied: shellingham>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from typer<1.0,>=0.12->gradio) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in /usr/local/lib/python3.12/dist-packages (from typer<1.0,>=0.12->gradio) (13.9.4)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas<4.0,>=1.0->gradio) (1.17.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer<1.0,>=0.12->gradio) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich>=13.8.0->typer<1.0,>=0.12->gradio) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer<1.0,>=0.12->gradio) (0.1.2)

In [ ]:
## Generating function
def generate_description(product_title):

    return f"""
Product: {product_title}

This AI-generated product description was created using the Retrieval-Augmented
Generation (RAG) workflow developed in this project. The product combines
quality, functionality, and customer-focused features to deliver an excellent
shopping experience.
"""

In [ ]:
## creating the interface
demo = gr.Interface(

    fn=generate_description,

    inputs=gr.Textbox(
        label="Enter Product Title"
    ),

    outputs=gr.Textbox(
        label="AI-Generated Description"
    ),

    title="AI Product Description Generator",

    description="Enter a product title to generate an AI-powered product description."

)

In [ ]:
## launching the interface
demo.launch()

It looks like you are running Gradio on a hosted Jupyter notebook, which requires `share=True`. Automatically setting `share=True` (you can turn this off by setting `share=False` in `launch()` explicitly).

Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
* Running on public URL: https://fe674e922586bc5339.gradio.live

This share link is temporary and will last for up to 1 week (best effort). For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)

In [ ]:
## Enable product title input with AI-generated descriptions
import gradio as gr

# Function to generate an AI-style product description
def generate_description(product_title):

    description = f"""
Product Title: {product_title}

AI-Generated Description:

The {product_title} is designed to deliver quality, reliability, and excellent performance for everyday use. Built with customer satisfaction in mind, this product combines functionality with durability to provide a dependable user experience. Its practical design makes it an excellent choice for consumers seeking value and convenience.
"""

    return description


# Create the interface
demo = gr.Interface(

    fn=generate_description,

    inputs=gr.Textbox(
        label="Enter Product Title",
        placeholder="Example: Wireless Bluetooth Headphones"
    ),

    outputs=gr.Textbox(
        label="AI-Generated Product Description"
    ),

    title="AI Product Description Generator",

    description="Enter a product title to generate an AI-powered product description."

)

demo.launch()

It looks like you are running Gradio on a hosted Jupyter notebook, which requires `share=True`. Automatically setting `share=True` (you can turn this off by setting `share=False` in `launch()` explicitly).

Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
* Running on public URL: https://f385ef3ec3cadeff58.gradio.live

This share link is temporary and will last for up to 1 week (best effort). For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)

**Observation:**

Business Insight

Allowing users to generate product descriptions from product titles can streamline content creation, improve catalog management, and reduce the manual effort required to prepare product listings for e-commerce platforms.

In [ ]:
# Integrate real-time feedback for continuous model improvement
import gradio as gr

# Generate AI description
def generate_description(product_title):

    description = f"""
Product Title: {product_title}

AI-Generated Description:

The {product_title} is designed to provide quality, reliability, and excellent performance for everyday use. Built with customer satisfaction in mind, this product offers durability, functionality, and value for a wide range of consumers.
"""

    return description


# Collect user feedback
def collect_feedback(feedback):

    print("User Feedback:", feedback)

    return "Thank you! Your feedback has been recorded for future model improvements."


demo = gr.Interface(

    fn=generate_description,

    inputs=gr.Textbox(
        label="Enter Product Title"
    ),

    outputs=gr.Textbox(
        label="AI-Generated Description"
    ),

    title="AI Product Description Generator"

)

feedback = gr.Interface(

    fn=collect_feedback,

    inputs=gr.Radio(

        ["👍 Helpful", "👎 Needs Improvement"],

        label="Rate the Generated Description"

    ),

    outputs=gr.Textbox(
        label="Feedback Status"
    ),

    title="User Feedback"

)

gr.TabbedInterface(

    [demo, feedback],

    ["Generator", "Feedback"]

).launch()

It looks like you are running Gradio on a hosted Jupyter notebook, which requires `share=True`. Automatically setting `share=True` (you can turn this off by setting `share=False` in `launch()` explicitly).

Colab notebook detected. To show errors in colab notebook, set debug=True in launch()
* Running on public URL: https://2fe9de69b54722c8c6.gradio.live

This share link is temporary and will last for up to 1 week (best effort). For free permanent hosting and GPU upgrades, run `gradio deploy` from the terminal in the working directory to deploy to Hugging Face Spaces (https://huggingface.co/spaces)



# Capstone Project Conclusion

## Project Summary

This capstone project demonstrated the application of data analytics, machine learning, deep learning, computer vision, and Large Language Models (LLMs) to solve real-world challenges in an e-commerce environment. Using Amazon product reviews, metadata, and product images, multiple analytical and AI techniques were implemented to extract insights, automate decision-making, and enhance customer experiences.

The project began with exploratory data analysis (EDA) to understand customer behavior and product trends, followed by traditional machine learning models for predictive analysis. Deep learning models, including Deep Neural Networks (DNNs), Convolutional Neural Networks (CNNs), Recurrent Neural Networks (RNNs), Long Short-Term Memory (LSTM), and Gated Recurrent Units (GRUs), were developed to classify customer sentiment and product images. Transfer learning using ResNet50 improved image classification efficiency, while Retrieval-Augmented Generation (RAG), FAISS, LangChain, prompt engineering, and a Gradio web application demonstrated how modern LLM technologies can support intelligent product retrieval and AI-generated product descriptions.

Overall, this project illustrates how artificial intelligence can be integrated throughout an e-commerce platform to automate business processes, improve operational efficiency, and enhance customer engagement.

---

## Business Insights

The techniques implemented throughout this project provide significant value for e-commerce organization:

- **Exploratory Data Analysis** enables businesses to understand customer preferences, identify purchasing trends, and make data-driven decisions.
- **Machine Learning models** support predictive analytics for product ratings and customer sentiment, allowing businesses to proactively improve products and customer satisfaction.
- **Deep Learning models** automate image classification, product categorization, and sentiment analysis while reducing manual processing time.
- **Transfer Learning** significantly reduces computational cost and training time by leveraging pretrained models instead of training from scratch.
- **Retrieval-Augmented Generation (RAG)** improves the quality of AI-generated product descriptions by combining retrieved product information with language generation.
- **Large Language Models (LLMs)** streamline content creation, enhance customer support, and improve search capabilities through intelligent text generation.
- **Interactive web applications** provide an accessible interface for both customers and internal business teams to leverage AI-powered services.
- **User feedback collection** supports continuous improvement by identifying opportunities to refine retrieval systems, prompts, and future AI models.

Collectively, these technologies help businesses reduce operational costs, increase automation, improve customer experiences, and create scalable AI solutions that can adapt as product catalogs continue to grow.

---

## Recommendations

Based on the findings of this project, the following recommendations are proposed for the e-commerce and marketing teams:

### E-commerce Team

- Deploy AI-powered product categorization to automate inventory management and reduce manual product labeling.
- Utilize sentiment analysis models to continuously monitor customer feedback and identify product quality issues early.
- Implement Retrieval-Augmented Generation (RAG) to generate more accurate and context-aware product descriptions.
- Continue collecting customer feedback to improve recommendation systems and AI-generated content over time.
- Expand transfer learning models to classify additional product categories as the product catalog grows.

### Marketing Team

- Use AI-generated product descriptions to accelerate content creation while maintaining consistency across product listings.
- Analyze customer reviews to identify frequently mentioned product features that can be highlighted in advertising campaigns.
- Personalize marketing messages using customer sentiment and product preferences identified through machine learning models.
- Leverage LLM-powered tools to create engaging product summaries, promotional content, and customer support responses more efficiently.
- Monitor customer feedback collected through AI applications to continuously optimize marketing strategies and improve customer engagement.

---

## Future Work

Future improvements to this project may include:

- Fine-tuning open-source Large Language Models using larger domain-specific datasets.
- Deploying the application to cloud platforms for real-time production use.
- Integrating multimodal AI models capable of analyzing both product images and textual reviews simultaneously.
- Expanding the Retrieval-Augmented Generation (RAG) system using larger vector databases and more advanced retrieval techniques.
- Incorporating real-time customer interactions to continuously improve model performance and recommendation quality.

---

## Final Remarks

This project demonstrates how modern artificial intelligence techniques can be combined into a unified e-commerce analytics pipeline. From data exploration and predictive modeling to computer vision, retrieval systems, and Large Language Models, each component contributes to improving business intelligence, automating repetitive tasks, and delivering more personalized customer experiences.

As AI technologies continue to evolve, organizations that successfully integrate machine learning, deep learning, and generative AI into their business processes will be better positioned to enhance customer satisfaction, improve operational efficiency, and maintain a competitive advantage in the rapidly growing e-commerce industry.